#!/usr/bin/env python3
"""Collect site/data/suites.json by asking each suite what it contains.

WHY THIS EXISTS (Phase 20c, ADR-0042). The map has carried a node per suite
since 20a, and what those nodes said about themselves was a sentence written
beside them in assets/topology-groups.json plus a count of FILES. A sentence
maintained next to the thing it describes is the defect Phase 20 exists to end -
five of them were found stale on one afternoon - and a file count is not an
inventory: two spec files can hold two tests or twenty.

So the inventory is COLLECTED, by the same tools that run the suites:

    pytest --collect-only        tests/unit, tests/api
    playwright test --list       tests/playwright/tests/{smoke,regression}
    assert_seed.py --list        tests/db

The db suite had no collector at all, which is why it got one rather than a
description (ADR-0042 D1): its checks are now a list of named callables and
`--list` prints the same list the run executes.

WHAT IS DERIVED AND WHAT IS WIRING. Which suites exist comes from
assets/topology-groups.json - the same editorial file the map's phases come
from, so the two cannot disagree about the set. HOW to collect each one lives in
COLLECTORS below, and the join is checked: a suite in the asset with no
collector, or a collector for a suite the asset does not name, is a refusal.

WHY NOT A PARSER. A regex over `def test_` and `test("...")` would run anywhere,
with no dependency and no version pin, and it would be a SECOND definition of
what a test is - true until the first parametrised case, skip mark or generated
title. The tools are the definition; this script only normalises what they say.
The cost is that collection needs the suites' dependencies, so the gate runs in
ci.yml's `tests` job, which already installs every one of them, rather than
beside the map's own gate in `checks` (ADR-0042 D2).

THE VERSIONS ARE COMPARED AND NOT RECORDED. `docker compose config --images app`
filtered by service on the devbox and ignored the filter on a GitHub runner, and
that cost this project a scan of the wrong image. Discovery through a tool is a
version-dependent fact, so the pinned version is read from the repository and
compared with the version actually invoked: a host collecting with a different
pytest is told so in a sentence instead of through a byte diff.

The version does NOT go into the output file, and that is the second decision
rather than an omission (ADR-0042 D3). Written there, it would turn every
dependency bump into DRIFT on a Dependabot branch the bot cannot fix — and say
nothing, because the set of tests would be identical. A bump that DOES change
what the map shows still reddens the gate, on the names themselves, which is the
only version-related thing a reader of the map can act on.

    python3 scripts/collect-suites.py           # write site/data/suites.json
    python3 scripts/collect-suites.py --check   # refuse if it would differ

Both forms need the collectors on the machine. `make suite-inventory` passes the
interpreters in: UNIT_PYTEST and API_PYTEST come from the Makefile's own venv
paths, so the venv location is defined once, where `make test-unit` defines it.
"""
import json
import os
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
GROUPS_FILE = ROOT / "assets/topology-groups.json"
OUT = ROOT / "site/data/suites.json"
PLAYWRIGHT_DIR = ROOT / "tests/playwright"

HEADER = (
    "GENERATED by scripts/collect-suites.py, by asking each suite what it contains: "
    "pytest --collect-only, playwright test --list, assert_seed.py --list. Do not edit: "
    "`make suite-inventory-check` collects again and fails if this file and the suites "
    "disagree. Nothing here is written by hand - a test's name is read from the test. "
    "No result appears in this file: passed, failed and duration are things a RUN says, "
    "and they arrive from the published reports. Until then every test is uncollected "
    "evidence of nothing but its own existence."
)

# How to ask each suite. The set of suites comes from the asset, not from here;
# this table is the invocation, and the two are joined with a refusal.
COLLECTORS = {
    "unit": {
        "how": "pytest",
        "interpreter_env": "UNIT_PYTEST",
        "pythonpath": "app:infra/self-service/src",
        "pin_file": "tests/unit/requirements.txt",
    },
    "api": {
        "how": "pytest",
        "interpreter_env": "API_PYTEST",
        "pythonpath": None,
        "pin_file": "tests/api/requirements.txt",
    },
    "smoke": {"how": "playwright", "project": "smoke"},
    "regression": {"how": "playwright", "project": "regression"},
    # Two copies on purpose: the local gate and the one baked into the image,
    # which is the copy stage and prod actually run. Both are collected and
    # compared - see collect_script() for why that is the interesting part.
    "db": {
        "how": "script",
        "files": ["tests/db/assert_seed.py", "app/scripts/assert_seed.py"],
        "observed_copy": "app/scripts/assert_seed.py",
    },
}


class Refusal(Exception):
    """Something is missing or ambiguous enough that collecting anything would lie."""


def run(cmd, cwd=None, env=None):
    """Run a collector. A collector that fails is a refusal, never an empty list."""
    merged = dict(os.environ)
    merged.update(env or {})
    try:
        p = subprocess.run(
            cmd, cwd=cwd or ROOT, env=merged, capture_output=True, text=True
        )
    except FileNotFoundError as e:
        raise Refusal(f"{cmd[0]} is not on this machine: {e}")
    if p.returncode != 0:
        raise Refusal(
            f"collector exited {p.returncode}: {' '.join(cmd)}\n"
            f"--- stdout ---\n{p.stdout.strip()}\n--- stderr ---\n{p.stderr.strip()}"
        )
    return p.stdout


# ------------------------------------------------------------------ versions


def pinned(pin_file: str, package: str) -> str:
    text = (ROOT / pin_file).read_text()
    m = re.search(rf"^{re.escape(package)}==([0-9][^\s#]*)", text, re.M)
    if not m:
        raise Refusal(f"{pin_file} does not pin {package}==<version>")
    return m.group(1)


def pinned_playwright() -> str:
    pkg = json.loads((PLAYWRIGHT_DIR / "package.json").read_text())
    v = pkg.get("devDependencies", {}).get("@playwright/test")
    if not v:
        raise Refusal("tests/playwright/package.json does not pin @playwright/test")
    return v.lstrip("^~")


def same_version(actual: str, pin: str, what: str) -> None:
    if actual != pin:
        raise Refusal(
            f"{what} version mismatch: the repository pins {pin}, this machine ran {actual}.\n"
            "Collected inventories from two versions are not comparable, and the gate "
            "would report the difference as drift in the suites."
        )


# ---------------------------------------------------------------- collectors


def collect_pytest(spec, suite_dir: str) -> list[dict]:
    interpreter = os.environ.get(spec["interpreter_env"], "")
    if not interpreter:
        raise Refusal(
            f"{spec['interpreter_env']} is not set. Run this through `make suite-inventory`, "
            "which passes the virtualenv the matching `make test-*` target builds."
        )
    if not pathlib.Path(interpreter).is_file():
        raise Refusal(
            f"{spec['interpreter_env']}={interpreter} does not exist. "
            "Build it first: `make test-unit` / `make test-api`."
        )

    version = run([interpreter, "--version"]).strip().split()[-1]
    same_version(version, pinned(spec["pin_file"], "pytest"), "pytest")

    env = {"PYTHONPATH": spec["pythonpath"]} if spec["pythonpath"] else {}
    out = run([interpreter, suite_dir, "--collect-only", "-q", "-p", "no:cacheprovider"], env=env)

    tests, counted = [], None
    for line in out.splitlines():
        line = line.strip()
        m = re.match(r"^(\S+\.py)::(.+)$", line)
        if m:
            tests.append({"file": m.group(1), "name": m.group(2)})
            continue
        m = re.match(r"^(\d+) tests? collected", line)
        if m:
            counted = int(m.group(1))

    # pytest prints the total itself. Parsing its per-test lines and ignoring
    # its own count would mean trusting this script's regex over the tool.
    if counted is None:
        raise Refusal(f"pytest printed no collection total for {suite_dir}")
    if counted != len(tests):
        raise Refusal(
            f"pytest collected {counted} tests in {suite_dir}, this script parsed {len(tests)}. "
            "The output format changed; fix the parser rather than the number."
        )
    return tests


def collect_playwright(spec, suite_dir: str) -> list[dict]:
    if not (PLAYWRIGHT_DIR / "node_modules").is_dir():
        raise Refusal(
            "tests/playwright/node_modules is missing. Run `npm install` there, or "
            "`make test-smoke`, before collecting."
        )
    version = run(["npx", "playwright", "--version"], cwd=PLAYWRIGHT_DIR).strip().split()[-1]
    same_version(version, pinned_playwright(), "@playwright/test")

    listed = json.loads(
        run(
            ["npx", "playwright", "test", "--list", "--reporter=json"],
            cwd=PLAYWRIGHT_DIR,
        )
    )
    if listed.get("errors"):
        raise Refusal("playwright reported errors while listing:\n" + json.dumps(listed["errors"], indent=2))

    tests = []

    def walk(node, titles):
        for sp in node.get("specs", []):
            # The file is reported relative to testDir; the map speaks in
            # repository paths, and so does every other generated file here.
            rel = "tests/playwright/tests/" + node.get("file", "")
            projects = {t.get("projectName") for t in sp.get("tests", [])}
            if projects != {spec["project"]}:
                continue
            # ADR-0025 binds a suite to a DIRECTORY. A spec answering to this
            # project from outside the directory would run in a suite the map
            # draws somewhere else, and nothing else in this repository looks.
            if not rel.startswith(suite_dir.rstrip("/") + "/"):
                raise Refusal(
                    f"spec {rel} runs in project '{spec['project']}' but lives outside {suite_dir}. "
                    "ADR-0025 binds the suite to the directory; the map would draw it in the wrong place."
                )
            tests.append({"file": rel, "name": " > ".join(titles + [sp["title"]])})
        for child in node.get("suites", []):
            walk(child, titles + [child.get("title", "")])

    for top in listed.get("suites", []):
        walk(top, [])
    return tests


def collect_script(spec) -> list[dict]:
    """Collect the db suite from BOTH copies, and refuse if they have drifted.

    The copy under app/scripts/ is the one stage and prod run, as an ECS task;
    tests/db/ is the local `make test-db` gate. Publishing an inventory from the
    local copy while the cloud runs the other one is a true description of a
    different program - the shape this whole phase is about. So the mirror is
    asserted here, where the inventory is built, rather than asked for in a
    comment at the top of each file (which is where it was asked for, and which
    is why both copies were free to drift for eleven phases).
    """
    seen = {}
    for rel in spec["files"]:
        path = ROOT / rel
        if not path.is_file():
            raise Refusal(f"{rel} does not exist")
        data = json.loads(run([sys.executable, str(path), "--list"]))
        seen[rel] = data.get("tests", [])

    first, *rest = spec["files"]
    for other in rest:
        if seen[other] != seen[first]:
            raise Refusal(
                f"the two copies of the db assertion disagree about their checks.\n"
                f"  {first}: {[t['name'] for t in seen[first]]}\n"
                f"  {other}: {[t['name'] for t in seen[other]]}\n"
                "They mirror each other on purpose; the cloud runs "
                f"{spec['observed_copy']}."
            )

    observed = seen[spec["observed_copy"]]
    return [
        {"file": spec["observed_copy"], "name": t["name"], "asserts": t["asserts"]}
        for t in observed
    ]


# --------------------------------------------------------------------- build


VERSIONS: dict[str, str] = {}


def build() -> dict:
    if not GROUPS_FILE.is_file():
        raise Refusal(f"{GROUPS_FILE.relative_to(ROOT)} does not exist")
    asset = json.loads(GROUPS_FILE.read_text()).get("suites") or {}
    if not asset:
        raise Refusal("assets/topology-groups.json names no suites. Refusing to report zero.")

    missing = sorted(set(asset) - set(COLLECTORS))
    extra = sorted(set(COLLECTORS) - set(asset))
    if missing:
        raise Refusal(
            f"no collector for suite(s): {', '.join(missing)}. A suite the map draws and "
            "nothing can be asked about is exactly what this file exists to prevent."
        )
    if extra:
        raise Refusal(f"collector(s) for suite(s) the map does not name: {', '.join(extra)}")

    suites = {}
    VERSIONS.clear()
    for name in sorted(asset):
        spec = COLLECTORS[name]
        suite_dir = asset[name]["dir"]
        if not (ROOT / suite_dir).is_dir():
            raise Refusal(f"suite directory {suite_dir} does not exist")

        if spec["how"] == "pytest":
            tests = collect_pytest(spec, suite_dir)
            VERSIONS["pytest"] = pinned(spec["pin_file"], "pytest")
        elif spec["how"] == "playwright":
            tests = collect_playwright(spec, suite_dir)
            VERSIONS["@playwright/test"] = pinned_playwright()
        else:
            tests = collect_script(spec)

        # The oldest refusal in this repository, and still the right one: a
        # collector that finds nothing is indistinguishable from a suite that
        # was deleted, and both render as a node with nothing in it.
        if not tests:
            raise Refusal(f"suite '{name}' collected zero tests. Refusing to report zero.")

        entry = {
            "dir": suite_dir,
            "collector": spec["how"],
            "count": len(tests),
            # COLLECTION ORDER, not sorted. Every collector here reports in the
            # order the suite runs - pytest by file then by definition,
            # playwright by file, the db checks by their tuple - and for the db
            # suite that order is the point: the row check cannot pass before
            # the table check. Sorting would be tidier and would throw away a
            # fact the run depends on.
            "tests": tests,
        }
        if spec["how"] == "playwright":
            entry["project"] = spec["project"]
        if spec["how"] == "script":
            entry["observed_copy"] = spec["observed_copy"]
            entry["mirrors"] = spec["files"]
        suites[name] = entry

    return {
        "_": HEADER,
        "schema": 1,
        "counts": {
            "suites": len(suites),
            "tests": sum(s["count"] for s in suites.values()),
        },
        "suites": suites,
    }


def main() -> int:
    check = "--check" in sys.argv[1:]
    try:
        data = build()
    except Refusal as e:
        print(f"suite-inventory: REFUSED\n{e}")
        return 1

    rendered = json.dumps(data, indent=2, ensure_ascii=False) + "\n"

    if not check:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(rendered)
        c = data["counts"]
        print(
            f"suite-inventory: wrote {OUT.relative_to(ROOT)} - "
            f"{c['tests']} tests across {c['suites']} suites "
            + ", ".join(f"{n} {s['count']}" for n, s in data["suites"].items())
        )
        return 0

    if not OUT.is_file():
        print(
            f"suite-inventory: REFUSED\n{OUT.relative_to(ROOT)} does not exist. "
            "The map fetches it; a missing file is a blank panel, not an empty one."
        )
        return 1
    if OUT.read_text() != rendered:
        print(
            f"suite-inventory: DRIFT\n{OUT.relative_to(ROOT)} disagrees with what the "
            "collectors just reported for tests/unit, tests/api, tests/db or "
            "tests/playwright/tests/.\nRun `make suite-inventory` and commit the result."
        )
        return 1

    c = data["counts"]
    # The versions are printed, not stored: the run's log is where a
    # provenance question is asked, and the log does not have to be
    # regenerated by hand when a bot bumps a pin.
    print(
        f"suite-inventory: clean - {c['tests']} tests across {c['suites']} suites, "
        f"collected with " + ", ".join(f"{k} {v}" for k, v in sorted(VERSIONS.items()))
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
