#!/usr/bin/env python3
"""Generate site/data/topology.json from infra/ and tests/, and check it has not drifted.

WHY THIS EXISTS. On 2026-08-08 eleven reader-facing places described the applied,
publicly-pressed `infra/self-service` as written-and-never-applied, and six of
them were COUNTS - "seven state levels", "twenty-seven ADRs" - which go stale
without a word changing around them and read as precision while they do. No
linter could have caught it: `make docs-check` verifies that every path a
document NAMES exists, never that what it CLAIMS is true. ADR-0039 D1 takes the
other route: the picture and its numbers are GENERATED from the repository, so
the class of defect ends instead of being policed.

WHAT IS DERIVED AND WHAT IS EDITORIAL. Everything countable comes from here:
which state levels exist, which modules each instantiates, how many resource
blocks that expands to, how many suites and spec files, how many ADRs and
workflows. Nothing countable is written by hand anywhere. The two things that
CANNOT be derived live in assets/topology-groups.json: which display group each
resource block belongs to, and how the groups are arranged into phases. That
file is editorial and says so.

THE GATE (`make site-data-check`) IS A COVERAGE GATE, NOT A DEPICTION ONE. It
does not know whether the map is a good picture. It knows that every resource
block under infra/ is assigned to exactly one display group - including the
groups that mean "deliberately not shown", which are green and recorded rather
than silently absent - and that the committed JSON is byte-identical to a fresh
generation. An unassigned resource is red; an assignment naming a resource that
no longer exists is red; a group whose resources live in a level no node draws
is red.

NO OBSERVATIONS ARE WRITTEN HERE. Durations, costs, identifiers and test results
are things a CYCLE says, not things the repository knows, and inventing them is
the defect this file exists to remove. They arrive in 20b from Terraform's own
`-json` event stream and in 20c from the published reports. Until then every node
renders as "no observation yet", which is true.

    python3 scripts/generate-topology.py            # write site/data/topology.json
    python3 scripts/generate-topology.py --check     # refuse if it would differ
"""
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
INFRA = ROOT / "infra"
MODULES = INFRA / "modules"
GROUPS_FILE = ROOT / "assets/topology-groups.json"
OUT = ROOT / "site/data/topology.json"

HEADER = (
    "GENERATED by scripts/generate-topology.py from infra/ and tests/. Do not edit: "
    "`make site-data-check` regenerates it and fails if this file and the repository "
    "disagree. Everything countable here is computed; the grouping and the phase "
    "arrangement come from assets/topology-groups.json, which is editorial and says so. "
    "No duration, cost, identifier or test result appears in this file - those are things "
    "a cycle says, and they arrive in 20b and 20c from Terraform's own event stream and "
    "from the published reports. Until then every node is honestly unobserved."
)


class Refusal(Exception):
    """Something is missing or ambiguous enough that generating anything would lie."""


# ---------------------------------------------------------------- terraform


def _strip(text: str) -> str:
    """Remove line comments, so a commented-out resource is not counted as one."""
    out = []
    for line in text.splitlines():
        in_str = False
        cut = len(line)
        i = 0
        while i < len(line):
            c = line[i]
            if c == '"' and (i == 0 or line[i - 1] != "\\"):
                in_str = not in_str
            elif not in_str and (line.startswith("#", i) or line.startswith("//", i)):
                cut = i
                break
            i += 1
        out.append(line[:cut])
    return "\n".join(out)


def _blocks(text: str, keyword: str):
    """Yield (labels, body) for every top-level `keyword "a" "b" { ... }` block.

    Brace-matched rather than regex-terminated: a body containing a nested block
    (every one of ours does) ends at the brace that balances, not at the first
    one on its own line.
    """
    for m in re.finditer(rf'^{keyword}\s+((?:"[^"]+"\s*)+)\{{', text, re.M):
        labels = re.findall(r'"([^"]+)"', m.group(1))
        depth, i, in_str = 1, m.end(), False
        while i < len(text) and depth:
            c = text[i]
            if c == '"' and text[i - 1] != "\\":
                in_str = not in_str
            elif not in_str:
                if c == "{":
                    depth += 1
                elif c == "}":
                    depth -= 1
            i += 1
        yield labels, text[m.end() : i - 1]


def _meta_at_top(body: str) -> bool:
    """True if `count` or `for_each` is a meta-argument OF THIS RESOURCE.

    Depth matters and indentation does not. `for_each` four spaces in, inside a
    `dynamic "ingress"` block, is an argument of that block and says nothing about
    how many security groups exist - and a regex anchored on indentation reports
    it, which is how the same check was first written wrong in Phase 19g. This
    walks the braces instead, so only depth zero counts.
    """
    depth, in_str, i = 0, False, 0
    while i < len(body):
        c = body[i]
        if c == '"' and body[i - 1] != "\\":
            in_str = not in_str
        elif not in_str:
            if c == "{":
                depth += 1
            elif c == "}":
                depth -= 1
            elif depth == 0 and re.match(r"(count|for_each)\s*=", body[i:]) and (i == 0 or not body[i - 1].isalnum() and body[i - 1] != "_" and body[i - 1] != "."):
                return True
        i += 1
    return False


def declarations(d: pathlib.Path):
    """Every resource block declared in one directory, as `type.name`, in file order.

    Returns (addresses, repeated), where `repeated` is the subset carrying `count`
    or `for_each` - one block, an unknown number of objects. They are counted as
    ONE here, which is why every one of them has to be acknowledged by name in the
    groups file: the number is the whole point of this generator, and a block that
    silently means five is the same species of defect as a stale count in prose.
    """
    found, repeated = [], []
    for f in sorted(d.glob("*.tf")):
        text = _strip(f.read_text())
        for labels, body in _blocks(text, "resource"):
            if len(labels) != 2:
                raise Refusal(f"{f}: a resource block with {len(labels)} labels")
            addr = f"{labels[0]}.{labels[1]}"
            found.append(addr)
            if _meta_at_top(body):
                repeated.append(addr)
        if list(_blocks(text, "module")) and MODULES in d.parents:
            raise Refusal(f"{f}: a module calling a module. Not supported; expansion is one level deep.")
    if len(set(found)) != len(found):
        raise Refusal(f"{d}: two resource blocks share one address")
    return found, repeated


def module_calls(d: pathlib.Path):
    """Every module instantiation in one level, as (call name, resolved directory)."""
    calls = []
    for f in sorted(d.glob("*.tf")):
        for labels, body in _blocks(_strip(f.read_text()), "module"):
            src = re.search(r'^\s+source\s*=\s*"([^"]+)"', body, re.M)
            if not src:
                raise Refusal(f"{f}: module {labels[0]} has no source")
            target = (d / src.group(1)).resolve()
            if not target.is_dir():
                raise Refusal(f"{f}: module {labels[0]} points at {src.group(1)}, which is not a directory")
            calls.append((labels[0], target))
    return calls


def levels():
    """Every Terraform ROOT level: a directory with .tf files that is not a module."""
    found = []
    for d in sorted(p for p in INFRA.rglob("*") if p.is_dir()):
        if d == MODULES or MODULES in d.parents or not list(d.glob("*.tf")):
            continue
        found.append(d)
    if not found:
        raise Refusal("no Terraform root level found under infra/. Refusing to report zero.")
    return found


def expand(level: pathlib.Path):
    """Every resource the level owns, as (terraform address, declaring directory, decl)."""
    rows = [(decl, level, decl) for decl in declarations(level)[0]]
    for name, target in module_calls(level):
        rows += [(f"module.{name}.{decl}", target, decl) for decl in declarations(target)[0]]
    return rows


# ------------------------------------------------------------------- suites


def spec_files(spec) -> int:
    d = ROOT / spec["dir"]
    if not d.is_dir():
        raise Refusal(f"suite directory {spec['dir']} does not exist")
    n = len(list(d.glob(spec["pattern"])))
    if not n:
        raise Refusal(f"suite {spec['dir']} matched no file for {spec['pattern']}. Refusing to report zero.")
    return n


# --------------------------------------------------------------- live phase
#
# ADR-0039 D4: a phase pulses while it is running, and the observer is the
# GitHub Actions API, which reports the running job and step anonymously. Every
# workflow here holds ONE job, so the job alone cannot tell "Build" from "Apply
# — stage": the binding has to name a STEP.
#
# A step name is a string in a YAML file, and a binding to a string that has
# quietly been renamed is a pulse that never fires again — silent, and invisible
# to every other gate in this repository. So the binding is verified here: a
# phase naming a step that its job does not have is a refusal, exactly like a
# node drawing a group that owns nothing.

WORKFLOWS = ROOT / ".github/workflows"
JOB_KEY = re.compile(r"^  ([A-Za-z0-9_.-]+):\s*$")
STEP_NAME = re.compile(r"^\s*-\s+name:\s*(.+?)\s*$")


def workflow_jobs(path: pathlib.Path) -> dict[str, list[str]]:
    """job id -> the step names it declares, read without a YAML library.

    Deliberately a superset: anything shaped like `- name:` inside a job block
    counts. The question asked of it is only ever "does this job declare a step
    with exactly this name", so a false positive would have to be a step that
    exists somewhere else in the same job — and a false NEGATIVE, which is the
    dangerous direction, cannot happen.
    """
    jobs: dict[str, list[str]] = {}
    current, in_jobs = None, False
    for line in path.read_text().splitlines():
        if line.startswith("jobs:"):
            in_jobs = True
            continue
        if in_jobs and line.strip() and not line.startswith(" "):
            break
        if not in_jobs:
            continue
        m = JOB_KEY.match(line)
        if m:
            current = m.group(1)
            jobs.setdefault(current, [])
            continue
        if current is None:
            continue
        s = STEP_NAME.match(line)
        if s:
            name = s.group(1)
            if len(name) > 1 and name[0] == name[-1] and name[0] in "\"'":
                name = name[1:-1]
            jobs[current].append(name)
    return jobs


def live_bindings(owner: str, spec: dict) -> tuple[list[dict], list[str]]:
    """Resolve and CHECK one owner's live bindings.

    The owner is a phase or a SUITE NODE, and the check is identical for both.
    A suite node binds its OWN step, because the phase it is drawn in may bind a
    different one: `suite.db.stage` is drawn in the quality gate and its report
    comes out of a step in Provision, so inheriting the phase's answer lit it in
    the wrong minute - and prod, whose gate phase does bind its db step, gave a
    different answer for the same suite (ADR-0043 D1).
    """
    findings: list[str] = []
    bindings = spec.get("live")
    if not bindings:
        # Nothing that can pulse is exempt. A phase or suite with no binding can
        # never pulse, and the map would show a cycle running with a hole in it.
        return [], [f"{owner} declares no `live` binding"]

    resolved = []
    for b in bindings:
        path = WORKFLOWS / b["workflow"]
        if not path.is_file():
            findings.append(f"{owner}: no workflow {b['workflow']}")
            continue
        jobs = workflow_jobs(path)
        if b["job"] not in jobs:
            findings.append(
                f"{owner}: {b['workflow']} has no job {b['job']} "
                f"(it has: {', '.join(sorted(jobs)) or 'none'})"
            )
            continue
        steps = b.get("steps", [])
        for step in steps:
            if step not in jobs[b["job"]]:
                findings.append(
                    f"{owner}: {b['workflow']} job {b['job']} has no step "
                    f"named {step!r}. Renaming a step breaks the pulse silently; "
                    f"this is that rename, caught."
                )
        when = b.get("when", "step")
        if when == "step" and not steps:
            findings.append(f"{owner}: {b['workflow']} binding names no step")
        if when not in ("step", "waiting"):
            findings.append(f"{owner}: unknown live trigger {when!r}")
        resolved.append(
            {
                "workflow": b["workflow"],
                "path": f".github/workflows/{b['workflow']}",
                "job": b["job"],
                "when": when,
                "steps": steps,
            }
        )
    return resolved, findings


# ---------------------------------------------------------------- assembly


def build():
    if not GROUPS_FILE.is_file():
        raise Refusal(f"{GROUPS_FILE.relative_to(ROOT)} is missing. It carries the grouping; nothing can be generated without it.")
    spec = json.loads(GROUPS_FILE.read_text())

    groups = {}
    for g in spec["groups"]:
        if g["id"] in groups:
            raise Refusal(f"two display groups share the id {g['id']}")
        groups[g["id"]] = g

    lv = levels()
    rel = {d: str(d.relative_to(ROOT)) for d in lv}
    owned = {d: expand(d) for d in lv}

    findings = []

    # 1. every resource block declared under infra/ is assigned exactly once.
    assign = spec["assign"]
    declared, repeated = {}, {}
    for d in lv:
        for site in [d] + [t for _, t in module_calls(d)]:
            rel_site = str(site.relative_to(ROOT))
            decls, reps = declarations(site)
            declared.setdefault(rel_site, set()).update(decls)
            for r in reps:
                repeated[f"{rel_site}::{r}"] = True

    # A block with count or for_each is acknowledged by name, with a reason, or the
    # gate is red. Adding one silently would make every number below quietly wrong.
    acknowledged = set(spec.get("repeated", {}))
    for addr in sorted(set(repeated) - acknowledged):
        findings.append(f"unacknowledged repetition: {addr} carries count or for_each and is counted as one block")
    for addr in sorted(acknowledged - set(repeated)):
        findings.append(f"stale repetition: {addr} is listed as repeated and no longer is")

    for site, decls in sorted(declared.items()):
        table = assign.get(site, {})
        for decl in sorted(decls):
            if decl not in table:
                findings.append(f"unassigned: {site} :: {decl} belongs to no display group")
            elif table[decl] not in groups:
                findings.append(f"unknown group: {site} :: {decl} -> {table[decl]}")
        for decl in sorted(set(table) - decls):
            findings.append(f"stale assignment: {site} :: {decl} is assigned but no longer declared")
    for site in sorted(set(assign) - set(declared)):
        findings.append(f"stale assignment: {site} declares nothing under infra/")

    def group_of(site_rel, decl):
        return assign.get(site_rel, {}).get(decl)

    def members_in(level_dir, group_id):
        return [
            addr
            for addr, site, decl in owned[level_dir]
            if group_of(str(site.relative_to(ROOT)), decl) == group_id
        ]

    def count_in(level_dir, group_id):
        return len(members_in(level_dir, group_id))

    # 2. every group that owns resources in a level is drawn by that level's phase,
    #    or is explicitly not shown. A module instantiated into a level nobody draws
    #    is exactly the drift this gate is for.
    drawn = {}
    for p in spec["phases"]:
        if "level" in p:
            drawn.setdefault(p["level"], set()).update(n["group"] for n in p["nodes"] if "group" in n)
    for d in lv:
        present = {
            group_of(str(site.relative_to(ROOT)), decl) for _, site, decl in owned[d]
        } - {None}
        for gid in sorted(present):
            g = groups.get(gid)
            if g is None:
                continue
            if g["kind"] == "permanent" or not g.get("shown", True):
                continue
            if gid not in drawn.get(rel[d], set()):
                findings.append(f"undrawn: group {gid} owns resources in {rel[d]}, which no phase node draws")

    # 3. a node whose group owns nothing in its level. The module was removed and
    #    the map still shows it.
    for p in spec["phases"]:
        for n in p["nodes"]:
            gid = n.get("group")
            if gid is None:
                continue
            if gid not in groups:
                findings.append(f"phase {p['id']} draws unknown group {gid}")
            elif count_in(ROOT / p["level"], gid) == 0:
                findings.append(f"empty node: group {gid} owns no resource in {p['level']}")

    if findings:
        raise Refusal("\n".join(findings))

    # ------------------------------------------------------------- the file
    permanent_levels = [d for d in lv if not str(d).startswith(str(INFRA / "envs"))]
    cycle_levels = [d for d in lv if d not in permanent_levels]

    perm_cards = []
    for g in spec["groups"]:
        if g["kind"] != "permanent":
            continue
        holders = [d for d in permanent_levels if count_in(d, g["id"])]
        if not holders:
            raise Refusal(f"permanent card {g['id']} owns no resource in any permanent level")
        perm_cards.append(
            {
                "id": g["id"],
                "label": g["label"],
                "service": g["service"],
                "level": " + ".join(rel[d] for d in holders),
                "resources": sum(count_in(d, g["id"]) for d in holders),
                "members": [f"{rel[d]} :: {a}" for d in holders for a in members_in(d, g["id"])],
                "why": g["why"],
            }
        )

    phases = []
    for p in spec["phases"]:
        nodes = []
        for n in p["nodes"]:
            if "group" in n:
                g = groups[n["group"]]
                nodes.append(
                    {
                        "id": f"{p['env']}.{g['id']}",
                        "label": g["label"],
                        "service": g["service"],
                        "kind": "service",
                        "env": p["env"],
                        "observer": "terraform",
                        "resources": count_in(ROOT / p["level"], g["id"]),
                        "members": members_in(ROOT / p["level"], g["id"]),
                    }
                )
            elif "suite" in n:
                s = spec["suites"][n["suite"]]
                # The node's OWN binding, checked exactly like a phase's. A
                # suite is observed by a step, and the step that produces its
                # report is not always in the phase the node is drawn in.
                node_live, node_findings = live_bindings(f"node {n['id']}", n)
                if node_findings:
                    raise Refusal("\n".join(node_findings))
                nodes.append(
                    {
                        "id": n["id"],
                        "label": n["label"],
                        "service": n["service"],
                        "kind": n["kind"],
                        "env": n.get("env", p.get("env")),
                        "observer": n["observer"],
                        "suite": n["suite"],
                        "suite_dir": s["dir"],
                        "asserts": s["asserts"],
                        "spec_files": spec_files(s),
                        "live": node_live,
                    }
                )
            elif "whole_level" in n:
                node = {k: v for k, v in n.items() if k != "whole_level"}
                node["resources"] = len(owned[ROOT / n["whole_level"]])
                node["level"] = n["whole_level"]
                nodes.append(node)
            else:
                node = dict(n)
                node.setdefault("env", p.get("env"))
                nodes.append(node)
        # THE TOOL, IN TEXT (ADR-0047 D4). Terraform, Docker, Playwright, pytest
        # and Alembic appear nowhere on the map, and that is the half of the
        # requirement icons could never answer. Derived where it is derivable - a
        # node observed by terraform is made by terraform - and editorial in
        # assets/topology-groups.json where it is not: nothing under infra/ says
        # that docker builds the image or that alembic migrates the database.
        # A SUITE'S TOOL IS NOT SET HERE at all: it is the `collector` in
        # site/data/suites.json, collected by asking the suite itself, and the
        # page reads it from there rather than keeping a second copy.
        for n in nodes:
            if "tool" not in n and n.get("observer") == "terraform":
                n["tool"] = "terraform"
        live, live_findings = live_bindings(f"phase {p['id']}", p)
        if live_findings:
            raise Refusal("\n".join(live_findings))
        phases.append(
            {
                "id": p["id"],
                "n": p["n"],
                "label": p["label"],
                "workflow": p["workflow"],
                "live": live,
                "nodes": nodes,
            }
        )

    # THE REQUEST PATH (ADR-0047 D1, the `where it lives` panel). The ORDER is
    # editorial and assets/topology-groups.json says so at length; everything
    # else is derived from what each hop CITES, so the panel cannot outlive the
    # thing it draws. A hop citing an id the map does not have is a refusal, not
    # a blank box: the failure mode this replaces is a hand-written architecture
    # strip that kept describing infrastructure after it was deleted, which is
    # the 2026-08-08 finding ADR-0039 D1 exists to close.
    known = {c["id"]: c for c in perm_cards}
    for p in phases:
        for n in p["nodes"]:
            known[n["id"]] = n
    rp = spec.get("request_path")
    if not rp or not rp.get("hops"):
        raise Refusal("assets/topology-groups.json has no `request_path`. The panel that shows where a request goes cannot be derived from infra/, and must not be invented by the page.")
    hops = []
    for h in rp["hops"]:
        cited = h.get("cites")
        if cited is None:
            if not h.get("label"):
                raise Refusal(f"hop {h['id']} cites nothing and has no label of its own")
            hops.append({"id": h["id"], "label": h["label"], "glyph": h.get("glyph"), "tools": h.get("tools", [])})
            continue
        if cited not in known:
            raise Refusal(f"hop {h['id']} cites {cited}, which is not a node or a permanent card on this map")
        src = known[cited]
        hops.append(
            {
                "id": h["id"],
                "cites": cited,
                "label": src["label"],
                "service": src.get("service"),
                "tools": h.get("tools", []),
            }
        )
    request_path = {"note": rp["note"], "editorial": rp["editorial"], "hops": hops}

    # THE MAP'S COLUMN SPAN TOTAL (ADR-0047 D5), COMPUTED. `repeat(auto-fit,
    # minmax(...))` chose a count that left phase 8 alone on a second row with a
    # screen of air beside it, so the count is deterministic instead - and the
    # total it needs is a fact about the data: six narrow phases and two wide
    # ones is ten columns TODAY. Writing ten into the stylesheet is the stale
    # literal ADR-0039 D1 exists to end, and the sketch carried it as one.
    #
    # A phase with WIDE_AT nodes or more takes two columns rather than twice the
    # height. The threshold is here and not in the CSS for the same reason: the
    # page must not be able to disagree with the number it was laid out from.
    WIDE_AT = 6
    wide = [p["id"] for p in phases if len(p["nodes"]) >= WIDE_AT]
    layout = {
        "wide_at": WIDE_AT,
        "wide": wide,
        "columns": len(phases) + len(wide),
    }

    not_shown = []
    for g in spec["groups"]:
        if g.get("shown", True):
            continue
        n = sum(count_in(d, g["id"]) for d in lv)
        if not n:
            raise Refusal(f"hidden group {g['id']} holds nothing. A group that hides nothing hides the fact that it hides nothing.")
        # The ADDRESSES, not only the count. scripts/node-states.py sorts every
        # resource a cycle touches into a node, into this list, or into
        # `unknown` - and without the addresses here it could only ever report
        # the third. A group that hides a resource has to be able to say WHICH.
        not_shown.append(
            {
                "group": g["id"],
                "label": g["label"],
                "resources": n,
                "why": g["why"],
                "members": sorted({a for d in lv for a in members_in(d, g["id"])}),
            }
        )

    # The band above the cycle: the two things a visitor cannot see in infra/
    # because neither is in it. A claim there is tied to a resource that must
    # exist - "GitHub reaches this account through OIDC" is checkable, and stops
    # being true the moment the provider is deleted.
    outside = spec.get("outside")
    if not outside or not outside.get("nodes"):
        raise Refusal("assets/topology-groups.json has no `outside` band. The devbox and GitHub are not in infra/, so nothing else can put them on the page.")
    for n in outside["nodes"]:
        backing = n.get("backed_by")
        if not backing:
            continue
        site, _, addr = backing.partition("::")
        if addr not in declared.get(site, set()):
            findings.append(f"unbacked claim: {n['id']} cites {backing}, which is not declared")
    if findings:
        raise Refusal("\n".join(findings))

    workflows = sorted(p.name for p in (ROOT / ".github/workflows").glob("*.yml"))
    adrs = list((ROOT / "docs/decisions").glob("*.md"))
    if not workflows or not adrs:
        raise Refusal("no workflows or no ADRs discovered. Refusing to report zero.")

    return {
        "_": HEADER,
        "schema": 2,
        "counts": {
            "levels": len(lv),
            "permanent_levels": len(permanent_levels),
            "cycle_levels": len(cycle_levels),
            "resources": sum(len(v) for v in owned.values()),
            "resources_permanent": sum(len(owned[d]) for d in permanent_levels),
            "resources_per_cycle": sum(len(owned[d]) for d in cycle_levels),
            "modules": len([p for p in MODULES.iterdir() if p.is_dir()]),
            "suites": len(spec["suites"]),
            "workflows": len(workflows),
            "adrs": len(adrs),
            "repeated_blocks": len(repeated),
        },
        "measured_cycle": None,
        "layout": layout,
        "request_path": request_path,
        "outside": outside,
        "permanent": perm_cards,
        "phases": phases,
        "not_shown": not_shown,
        "repeated": [
            {"address": a, "why": spec["repeated"][a]} for a in sorted(repeated)
        ],
    }


def main() -> int:
    check = "--check" in sys.argv[1:]
    try:
        data = build()
    except Refusal as e:
        print(f"site-data: REFUSED\n{e}")
        return 1

    rendered = json.dumps(data, indent=2, ensure_ascii=False) + "\n"

    if not check:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(rendered)
        c = data["counts"]
        print(
            f"site-data: wrote {OUT.relative_to(ROOT)} - {c['levels']} levels, "
            f"{c['resources']} resources, {c['suites']} suites, {c['adrs']} ADRs"
        )
        return 0

    if not OUT.is_file():
        print(f"site-data: REFUSED\n{OUT.relative_to(ROOT)} does not exist. The page fetches it; a missing file is a blank map, not an empty one.")
        return 1
    if OUT.read_text() != rendered:
        print(
            # EVERY source it reads, because the message is what a reader goes
            # looking with. On 2026-08-08 it fired on a new ADR and sent the
            # reader to infra/ and tests/, where nothing had changed. A message
            # that names the wrong directory is the same defect as a step whose
            # name lies about what it checks.
            f"site-data: DRIFT\n{OUT.relative_to(ROOT)} disagrees with "
            "infra/, tests/, .github/workflows/ or docs/decisions/.\n"
            "Run `make site-data` and commit the result."
        )
        return 1

    c = data["counts"]
    print(
        f"site-data: clean - every resource assigned; {c['resources']} across {c['levels']} levels "
        f"({c['resources_permanent']} permanent, {c['resources_per_cycle']} per cycle), "
        f"{sum(g['resources'] for g in data['not_shown'])} deliberately not shown"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
