#!/usr/bin/env python3
"""Point the four remaining consumers at site/data/topology.json's schema 3.

Phase 22 split the map's data into three contours - `estate` (what exists),
`cycle` (what a run does to it) and `assertions` (what is claimed about it).
The generator and its gate moved together, so `make site-data-check` went green
and stayed green. Four readers did not move, and NONE of them went red, because
every one of them is gated against a FROZEN schema-2 fixture:

    scripts/node-states.py            four indexers walking phases[].nodes.
                                      index_members() returned ZERO addresses
                                      against the real file - every resource of
                                      a live cycle would have been reported
                                      UNKNOWN, which is the one channel that is
                                      supposed to be rare
    assets/index.template.html        DATA.phases and p.nodes: the map would
                                      have thrown on load
    scripts/fold-results.py           the suite ids, read through
                                      topology["phases"] (the gate over it is
                                      scripts/check-results.py)
    tests/fixtures/live-state/        refresh.py, which regenerates the frozen
                                      phase snapshot from the real file

A green gate over a frozen fixture proves that the fixture and the code agree.
It says nothing about the file the code will actually be handed, and that is
the whole reason this script exists rather than a hand edit per site.

WHY A SCRIPT AND NOT A HEREDOC
------------------------------
docs/session-primer.md: prefer a checked-in patch script over a long
interactive heredoc, because it fails loudly and changes nothing on mismatch.

AND THE FAILURE THAT SHAPE HAS ALREADY HAD HERE. Phase 19g's patch script
computed every replacement FROM THE ORIGINAL TEXT and wrote them one after
another, so the second edit to a file silently discarded the first - and it
printed success twice (docs/phase-gates.md, Phase 19g). So: each file is read
ONCE into a string, every edit for that file is applied to THAT STRING in
sequence, and the string is written ONCE. No replacement is ever recomputed
from the text on disk.

THE REFUSAL CONTRACT
--------------------
    every anchor matches EXACTLY ONCE      -> everything is written
    an anchor matches 0 or 2+ times        -> NOTHING is written, exit 2
    every anchor is already gone and every
    replacement is already present         -> exit 3, "already applied"
    some applied and some not              -> NOTHING is written, exit 2

Exit 3 is a refusal too, and a loud one - it exists so that
scripts/verify-schema3.sh can be run twice without the second run reading as a
failure. A half-migrated tree is never a state this script can leave behind:
the writes happen after every edit in every file has been proved to match.

    scripts/migrate-schema3.py            # apply
    scripts/migrate-schema3.py --dry-run  # prove the anchors match, write nothing

AFTERWARDS, and NOT as a string edit: tests/fixtures/live-state/phases.json is
GENERATED by tests/fixtures/live-state/refresh.py. This script patches the
generator and then runs it. Hand-writing the snapshot beside its generator
would be a second definition of the same thing, which is the shape this
repository keeps deleting.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


class Refusal(Exception):
    """Anything that means: change nothing, say why, exit non-zero."""


class AlreadyApplied(Exception):
    """This file is already migrated. Not an error on its own; see the contract."""


# ----------------------------------------------------------------- text edits
#
# (anchor, replacement). The anchors carry surrounding lines wherever the line
# on its own is not unique - `DATA.phases.forEach((p) => {` appears in render()
# and in paint(), and an edit that matched both would have been applied to
# whichever came first and reported as one.

NODE_STATES = "scripts/node-states.py"
TEMPLATE = "assets/index.template.html"
FOLD_RESULTS = "scripts/fold-results.py"
REFRESH = "tests/fixtures/live-state/refresh.py"
LIVE_STATE_GATE = "scripts/check-live-state.mjs"
PAGE_TENSE_GATE = "scripts/check-page-tense.mjs"

EDITS: dict[str, list[tuple[str, str]]] = {}

# --- scripts/node-states.py --------------------------------------------------

EDITS[NODE_STATES] = [
    (
        """THE RULE, IN FULL
-----------------
""",
        """WHERE THE NODES COME FROM (schema 3)
------------------------------------
The map's data is three contours, and the join needs two of them:

    estate.environments[].nodes   the RESOURCE nodes. `resources` and `members`
                                  are properties of a state level, so they live
                                  here and nowhere else
    cycle.phases[].nodes          the VERB nodes - the image push, the migrate
                                  task, the suites, the teardown. Nothing
                                  Terraform reports as a resource
    cycle.phases[].touches        a phase's REFERENCE to an estate node, as
                                  {node, verb}. A reference and not a node the
                                  phase owns: three phases touch stage.rds, and
                                  only the one whose verb is `creates` is the
                                  phase that DRAWS it

Until 22 this file walked `phases[].nodes` for all four of its indexes. Against
the schema-3 file that is a list of verb nodes, not one of which carries a
member, so index_members() returned an EMPTY dict and every resource of a live
cycle would have been reported unknown. Every gate stayed green: the fixture
under tests/fixtures/node-states/ was still schema 2.

THE RULE, IN FULL
-----------------
""",
    ),
    (
        '''def index_members(topology: dict, environment: str) -> dict[str, str]:
    """Normalised member address -> node id, for ONE environment.

    Filtering by environment is not tidiness. `stage.vpc` and `prod.vpc` hold
    the SAME member addresses — they are the same modules in two state levels —
    so an index built across both would map every address to whichever node was
    seen last, and half the map would light from the other environment's cycle.
    """
    index: dict[str, str] = {}
    for phase in topology.get("phases", []):
        for node in phase.get("nodes", []):
            if node.get("env") != environment:
                continue
            for member in node.get("members", []) or []:
                index[base_address(member)] = node["id"]
    return index
''',
        '''def estate_nodes(topology: dict, environment: str) -> list[dict]:
    """The RESOURCE nodes of one environment, out of the estate contour.

    Read off the node's own `env` rather than off the environment it is listed
    under. The two agree today and the generator is what keeps them agreeing;
    a node that disagreed with its level would otherwise land silently in the
    other environment's index, which is the failure the filter below exists to
    prevent in the first place.
    """
    return [
        node
        for environment_entry in topology.get("estate", {}).get("environments", []) or []
        for node in environment_entry.get("nodes", []) or []
        if node.get("env") == environment
    ]


def cycle_nodes(topology: dict) -> list[tuple[str, dict]]:
    """(phase id, node) for every VERB node, in phase order."""
    return [
        (phase["id"], node)
        for phase in topology.get("cycle", {}).get("phases", []) or []
        for node in phase.get("nodes", []) or []
    ]


def creates(topology: dict) -> list[tuple[str, str]]:
    """(phase id, estate node id) for every touch whose verb is `creates`.

    The other four verbs are not drawing. `provisions`, `asserts` and
    `destroys` name a node some other phase made, and a resolver that took any
    touch would put stage.rds in four phases at once - which is the picture the
    contour split was made to end.
    """
    return [
        (phase["id"], touch["node"])
        for phase in topology.get("cycle", {}).get("phases", []) or []
        for touch in phase.get("touches", []) or []
        if touch.get("verb") == "creates"
    ]


def index_members(topology: dict, environment: str) -> dict[str, str]:
    """Normalised member address -> node id, for ONE environment.

    Filtering by environment is not tidiness. `stage.vpc` and `prod.vpc` hold
    the SAME member addresses — they are the same modules in two state levels —
    so an index built across both would map every address to whichever node was
    seen last, and half the map would light from the other environment's cycle.
    """
    index: dict[str, str] = {}
    for node in estate_nodes(topology, environment):
        for member in node.get("members", []) or []:
            index[base_address(member)] = node["id"]
    return index
''',
    ),
    (
        '''def phase_of(topology: dict, environment: str) -> dict[str, str]:
    """node id -> the phase that draws it, for this environment."""
    index: dict[str, str] = {}
    for phase in topology.get("phases", []):
        for node in phase.get("nodes", []):
            if node.get("env") == environment:
                index[node["id"]] = phase["id"]
    return index


def destroy_node(topology: dict, environment: str) -> str | None:
    for phase in topology.get("phases", []):
        for node in phase.get("nodes", []):
            if node.get("service") == "destroy" and node.get("env") == environment:
                return node["id"]
    return None
''',
        '''def phase_of(topology: dict, environment: str) -> dict[str, str]:
    """node id -> the phase that draws it, for this environment.

    Two contours, one answer, and it has to be the SAME answer the page gets
    from phaseNodes(): a phase's duration is measured over the nodes a reader
    is looking at inside it, so a resource resolved into one phase here and
    drawn in another there would put a number under the wrong heading.
    """
    index: dict[str, str] = {}
    for phase_id, node in cycle_nodes(topology):
        if node.get("env") == environment:
            index[node["id"]] = phase_id
    owned = {node["id"] for node in estate_nodes(topology, environment)}
    for phase_id, node_id in creates(topology):
        if node_id in owned:
            index[node_id] = phase_id
    return index


def destroy_node(topology: dict, environment: str) -> str | None:
    """The teardown node — a VERB node, so the cycle contour and not the estate."""
    for _phase_id, node in cycle_nodes(topology):
        if node.get("service") == "destroy" and node.get("env") == environment:
            return node["id"]
    return None
''',
    ),
]

# --- scripts/fold-results.py -------------------------------------------------

EDITS[FOLD_RESULTS] = [
    (
        """    node_ids = {
        n["id"] for phase in topology["phases"] for n in phase["nodes"] if n.get("kind") == "suite"
    }
""",
        """    # A suite is something a cycle DOES, so its node lives in the cycle contour
    # (schema 3) beside the image push and the teardown - never in the estate,
    # which is what exists between runs. Read through topology["phases"] this
    # raised KeyError against the real file and nothing noticed: the gate over
    # this fold reads a frozen stub, and the stub was still schema 2.
    node_ids = {
        n["id"]
        for phase in topology["cycle"]["phases"]
        for n in phase["nodes"]
        if n.get("kind") == "suite"
    }
""",
    ),
]

# --- assets/index.template.html ---------------------------------------------
#
# ONE resolver, and every read site routed through it. Layout, CSS, breakpoints
# and the composition are untouched on purpose - that is Phase 23, and the
# rendered page after this patch is geometrically identical because `creates`
# reproduces exactly the node list schema 2 wrote inline.

EDITS[TEMPLATE] = [
    # 1. the resolver itself, inside the lifted RUN-LAYER block.
    (
        """        /* Every phase and every node, in one pass. A node with its own binding
           answers for itself; a node without one inherits its phase's state and
           is MARKED as having done so, because the two must not render alike. */
        function runLayerStates(observation, phases) {""",
        """        /* THE TWO CONTOURS, JOINED, ONCE (schema 3). A phase holds the VERB
           nodes it owns and REFERENCES the resource nodes it acts on, as
           `touches: [{node, verb}]`. Only `creates` puts a node inside a
           phase: `provisions`, `asserts` and `destroys` name a node some other
           phase made, and taking any touch would draw stage.rds in four phases
           at once - the picture the split was made to end.

           EVERY READ SITE GOES THROUGH phaseNodes(). The map, the text under
           the cut, the paint pass and the state machine below deciding for
           themselves which nodes are in a phase is one definition on four
           hosts, which is the shape that has already cost this project a scan
           of the wrong image.

           The estate is a module-level binding and not a parameter because
           runLayerStates(observation, phases) KEEPS ITS SIGNATURE:
           scripts/check-live-state.mjs lifts this block out of the built page
           and calls it with two arguments, and a third one would leave the
           gate running code the visitor's browser does not. The page sets it
           when topology.json lands; the gate sets it from the frozen snapshot
           beside its cases. */
        let ESTATE_NODES = {};
        function useEstate(estate) {
          ESTATE_NODES = {};
          const half = (estate && estate.environments) || [];
          const all = ((estate && estate.permanent) || []).concat(
            half.reduce((a, e) => a.concat(e.nodes || []), [])
          );
          all.forEach((n) => { ESTATE_NODES[n.id] = n; });
        }
        function phaseNodes(p) {
          const own = (p && p.nodes) || [];
          const made = ((p && p.touches) || [])
            .filter((t) => t.verb === "creates")
            .map((t) => ESTATE_NODES[t.node])
            // An unresolvable reference is dropped rather than drawn as a
            // hole. It cannot arrive from the generator - the ids on both
            // sides come from one read of assets/topology-groups.json - and
            // the gate that would catch one is site-data-check, not the page.
            .filter(Boolean);
          return own.concat(made);
        }

        /* Every phase and every node, in one pass. A node with its own binding
           answers for itself; a node without one inherits its phase's state and
           is MARKED as having done so, because the two must not render alike. */
        function runLayerStates(observation, phases) {""",
    ),
    # 2. the state machine reads the resolved list.
    (
        """            if (ph.state) out.phases[p.id] = { state: ph.state, since: ph.since };
            (p.nodes || []).forEach((n) => {""",
        """            if (ph.state) out.phases[p.id] = { state: ph.state, since: ph.since };
            phaseNodes(p).forEach((n) => {""",
    ),
    # 3. the map: DATA.phases is gone, and the width is measured on the
    #    resolved list or `Apply - stage` would stop being a wide phase.
    (
        """          const want = layout.columns || DATA.phases.length;""",
        """          const want = layout.columns || DATA.cycle.phases.length;""",
    ),
    (
        """          DATA.phases.forEach((p) => {
            // A phase with six or more nodes takes two columns instead of twice
            // the height - unless the map has folded to one column, where two of
            // anything is not on offer.
            const wide = p.nodes.length >= wideAt && cols >= 2;""",
        """          DATA.cycle.phases.forEach((p) => {
            // Resolved ONCE per phase: the width, the tools, the shared word and
            // the drawing all have to be looking at the same list, and a phase
            // that measured itself on p.nodes alone would have found `Apply -
            // stage` empty and stopped being wide.
            const pn = phaseNodes(p);
            // A phase with six or more nodes takes two columns instead of twice
            // the height - unless the map has folded to one column, where two of
            // anything is not on offer.
            const wide = pn.length >= wideAt && cols >= 2;""",
    ),
    (
        """            const tools = [];
            p.nodes.forEach((n) => {""",
        """            const tools = [];
            pn.forEach((n) => {""",
    ),
    (
        """            const drawn = p.nodes.map((n) => nodeEl(n));
            const words = drawn.map((e) => e.dataset.word || "");
            const sharedWord = words.length > 1 && words.every((w) => w && w === words[0]) ? words[0] : null;
            const envs = p.nodes.map((n) => n.env || "");
            const sharedEnv = envs.length > 1 && envs.every((e) => e && e === envs[0]) ? envs[0] : null;
            const nodes = sharedWord || sharedEnv
              ? p.nodes.map((n) => nodeEl(n, { word: sharedWord, env: sharedEnv }))
              : drawn;""",
        """            const drawn = pn.map((n) => nodeEl(n));
            const words = drawn.map((e) => e.dataset.word || "");
            const sharedWord = words.length > 1 && words.every((w) => w && w === words[0]) ? words[0] : null;
            const envs = pn.map((n) => n.env || "");
            const sharedEnv = envs.length > 1 && envs.every((e) => e && e === envs[0]) ? envs[0] : null;
            const nodes = sharedWord || sharedEnv
              ? pn.map((n) => nodeEl(n, { word: sharedWord, env: sharedEnv }))
              : drawn;""",
    ),
    # 4. the paint pass.
    (
        """          const states = runLayerStates(RUNSTATE.observation, DATA.phases);
          RUNSTATE.phase = states.phases;
          RUNSTATE.node = states.nodes;
          DATA.phases.forEach((p) => {
            p.nodes.forEach((n) => {""",
        """          const states = runLayerStates(RUNSTATE.observation, DATA.cycle.phases);
          RUNSTATE.phase = states.phases;
          RUNSTATE.node = states.nodes;
          DATA.cycle.phases.forEach((p) => {
            // The measured figures are hung on the node OBJECTS, which the
            // estate owns and the resolver hands out by reference - so a
            // resource keeps what a cycle said about it however many phases
            // name it.
            phaseNodes(p).forEach((n) => {""",
    ),
    # 5. the text under the cut.
    (
        """          d.phases.forEach((p) => {
            h += `<h3>${p.n}. ${esc(p.label)} <span class="note">${esc(p.workflow)}</span></h3>`;
            h += dl(
              p.nodes.map((n) => {""",
        """          d.cycle.phases.forEach((p) => {
            h += `<h3>${p.n}. ${esc(p.label)} <span class="note">${esc(p.workflow)}</span></h3>`;
            h += dl(
              phaseNodes(p).map((n) => {""",
    ),
    (
        """            d.permanent.map((c) => [""",
        """            d.estate.permanent.map((c) => [""",
    ),
    (
        """            d.permanent.map((n) => `<span>${n.label}</span>`).join("") +""",
        """            d.estate.permanent.map((n) => `<span>${n.label}</span>`).join("") +""",
    ),
    (
        """            d.permanent.forEach((n) => {""",
        """            d.estate.permanent.forEach((n) => {""",
    ),
    # 6. the estate is handed to the resolver at the same moment DATA is set,
    #    and before paint() - which resolves.
    (
        """          .then((d) => {
            DATA = d;
            paint();""",
        """          .then((d) => {
            DATA = d;
            // BEFORE paint(), which resolves: a paint against an empty estate
            // would draw `Apply - stage` as an empty phase and light nothing.
            useEstate(d.estate);
            paint();""",
    ),
    # 7. UNRELATED to the restructuring, and cheap. The badge over the run
    #    history counted failures among COMPLETED runs and divided them by ALL
    #    runs, so a cycle in flight - the state the page is in whenever anybody
    #    is watching one - was counted as a success.
    (
        """        function nodeTense(node, record, envs, underWay) {""",
        """        /* A RUN THAT HAS NOT FINISHED HAS NOT SUCCEEDED. The badge over the run
           history read `all 12 succeeded` while one of the twelve was still
           going: its numerator was failures among COMPLETED runs and its
           denominator was every run in the list, so an in-flight cycle scored
           as a success until it ended. Same species as the three findings
           above - a figure about one moment printed as though it were about
           now - which is why it is answered here and not in the renderer.

           Counts and no words: the caller writes the sentence, so a change to
           how the badge reads cannot silently change what it COUNTS. */
        function historyTally(runs) {
          const all = runs || [];
          const finished = all.filter((r) => r && r.status === "completed");
          const failed = finished.filter((r) => r.conclusion !== "success");
          return {
            runs: all.length,
            finished: finished.length,
            failed: failed.length,
            unfinished: all.length - finished.length,
          };
        }

        function nodeTense(node, record, envs, underWay) {""",
    ),
    (
        """        var bad = runs.filter(function (r) {
          return r.status === "completed" && r.conclusion !== "success";
        }).length;
        var newest = runs[0];
        summary(
          '<span class="verdict ' + (bad ? "bad" : "ok") + '">' +
          (bad ? bad + " of " + runs.length + " failed" : "all " + runs.length + " succeeded") +
          '</span><span class="small">last: ' + esc(newest.name || newest.display_title) + " #" +""",
        """        // The denominator is the FINISHED runs, never the whole list: see
        // historyTally() in the PAGE TENSE block for what that was printing.
        // A list with nothing finished in it gets neither verdict - `all 0
        // succeeded` is a green badge over no evidence at all.
        var tally = historyTally(runs);
        var newest = runs[0];
        summary(
          '<span class="verdict ' + (tally.failed ? "bad" : tally.finished ? "ok" : "warn") + '">' +
          (tally.failed
            ? tally.failed + " of " + tally.finished + " failed"
            : tally.finished
            ? "all " + tally.finished + " succeeded"
            : "none of " + tally.runs + " has finished") +
          (tally.unfinished ? " &middot; " + tally.unfinished + " still going" : "") +
          '</span><span class="small">last: ' + esc(newest.name || newest.display_title) + " #" +""",
    ),
]

# --- tests/fixtures/live-state/refresh.py ------------------------------------

EDITS[REFRESH] = [
    (
        '''It rewrites `phases.json` from site/data/topology.json, keeping only what the
run-layer state machine reads: each phase's live binding, and each node's id,
environment and own binding.
''',
        '''It rewrites `phases.json` from site/data/topology.json, keeping only what the
run-layer state machine reads: each phase's live binding, each node's id,
environment and own binding, the phase's `touches`, and the estate nodes those
touches name.

THE TOUCHES ARE KEPT WHOLE, all five verbs. phaseNodes() takes only `creates`,
and a snapshot that pre-filtered them would be asserting that rule instead of
testing it: with every verb in the file, a resolver that forgot to filter
lights fifteen resource nodes in the teardown and the cases say so.
''',
    ),
    (
        '''def main() -> None:
    topology = json.loads((ROOT / "site/data/topology.json").read_text())
    phases = [
        {
            "id": p["id"],
            "live": p["live"],
            "nodes": [
                {k: v for k, v in n.items() if k in ("id", "env", "live")} for n in p["nodes"]
            ],
        }
        for p in topology["phases"]
    ]
    out = {"_": NOTE, "captured_from": "site/data/topology.json", "phases": phases}
    (HERE / "phases.json").write_text(json.dumps(out, indent=2) + "\\n")
    print(f"phases.json: {len(phases)} phases, "
          f"{sum(1 for p in phases for n in p['nodes'] if n.get('live'))} nodes with a binding of their own")
''',
        '''def keep(node: dict) -> dict:
    return {k: v for k, v in node.items() if k in ("id", "env", "live")}


def main() -> None:
    topology = json.loads((ROOT / "site/data/topology.json").read_text())
    phases = [
        {
            "id": p["id"],
            "live": p["live"],
            "nodes": [keep(n) for n in p["nodes"]],
            "touches": p.get("touches", []),
        }
        for p in topology["cycle"]["phases"]
    ]
    environments = [
        {"id": e["id"], "nodes": [keep(n) for n in e["nodes"]]}
        for e in topology["estate"]["environments"]
    ]

    # A touch that resolves to nothing would quietly shrink the node list this
    # gate folds, and a gate that checks fewer things than it did is the one
    # failure this repository will not see. So it is an error here, where the
    # snapshot is made, rather than a `filter(Boolean)` on the page.
    known = {n["id"] for e in environments for n in e["nodes"]}
    known |= {n["id"] for n in topology["estate"]["permanent"]}
    dangling = sorted(
        t["node"] for p in phases for t in p["touches"] if t["node"] not in known
    )
    if dangling:
        raise SystemExit(f"touches name estate nodes that do not exist: {dangling}")

    out = {
        "_": NOTE,
        "captured_from": "site/data/topology.json",
        "estate": {"environments": environments},
        "phases": phases,
    }
    (HERE / "phases.json").write_text(json.dumps(out, indent=2, ensure_ascii=False) + "\\n")
    print(f"phases.json: {len(phases)} phases, "
          f"{sum(1 for p in phases for n in p['nodes'] if n.get('live'))} nodes with a binding of their own, "
          f"{sum(len(e['nodes']) for e in environments)} estate nodes across "
          f"{len(environments)} environments")
''',
    ),
    (
        '''NOTE = (
    "A FROZEN snapshot of what the run-layer state machine needs out of "
    "site/data/topology.json: the phase bindings, and each node's id, "
    "environment and own binding. ''',
        '''NOTE = (
    "A FROZEN snapshot of what the run-layer state machine needs out of "
    "site/data/topology.json: the phase bindings, each node's id, "
    "environment and own binding, each phase's touches, and the estate nodes "
    "those touches name — the machine resolves them through phaseNodes(). ''',
    ),
]

# --- scripts/check-live-state.mjs -------------------------------------------

EDITS[LIVE_STATE_GATE] = [
    (
        """ *     site/index.html
 *       ==== RUN-LAYER STATE MACHINE - begin ====
 *         bindingState(observation, bindings)
 *         runLayerStates(observation, phases)
 *       ==== RUN-LAYER STATE MACHINE - end ====
""",
        """ *     site/index.html
 *       ==== RUN-LAYER STATE MACHINE - begin ====
 *         useEstate(estate)
 *         phaseNodes(p)
 *         bindingState(observation, bindings)
 *         runLayerStates(observation, phases)
 *       ==== RUN-LAYER STATE MACHINE - end ====
 *
 * Since schema 3 a phase REFERENCES the resource nodes it acts on instead of
 * holding them, so the snapshot carries an `estate` beside its phases and this
 * gate hands it over with useEstate() before folding anything. That is the one
 * call the page makes too, in the same order, for the same reason: without it
 * `Apply - stage` is an empty phase and the machine lights nothing.
""",
    ),
    (
        """  const context = vm.createContext({});
  try {
    vm.runInContext(source + "\\n;({ bindingState, runLayerStates })", context, {
      filename: "site/index.html#run-layer",
    });
  } catch (e) {
    refuse(`the extracted block does not evaluate: ${e}`);
  }
  const api = vm.runInContext("({ bindingState, runLayerStates })", context);
  if (typeof api.runLayerStates !== "function" || typeof api.bindingState !== "function") {
    refuse("the extracted block defines no bindingState/runLayerStates");
  }
  return api;""",
        """  const context = vm.createContext({});
  const EXPORTS = "({ bindingState, runLayerStates, useEstate, phaseNodes })";
  try {
    vm.runInContext(source + "\\n;" + EXPORTS, context, {
      filename: "site/index.html#run-layer",
    });
  } catch (e) {
    refuse(`the extracted block does not evaluate: ${e}`);
  }
  const api = vm.runInContext(EXPORTS, context);
  for (const name of ["bindingState", "runLayerStates", "useEstate", "phaseNodes"]) {
    if (typeof api[name] !== "function") refuse(`the extracted block defines no ${name}`);
  }
  return api;""",
    ),
    (
        """  const { runLayerStates } = loadStateMachine();

  const phasesFile = path.join(FX, "phases.json");
  if (!fs.existsSync(phasesFile)) refuse(`${path.relative(ROOT, phasesFile)} does not exist`);
  const phases = readJSON(phasesFile).phases;
""",
        """  const { runLayerStates, useEstate } = loadStateMachine();

  const phasesFile = path.join(FX, "phases.json");
  if (!fs.existsSync(phasesFile)) refuse(`${path.relative(ROOT, phasesFile)} does not exist`);
  const snapshot = readJSON(phasesFile);
  const phases = snapshot.phases;
  // A snapshot with no estate resolves every `creates` touch to nothing, and a
  // machine that reports nothing at all still passes a subset check - so the
  // absence is a refusal rather than a quiet zero. Regenerate it with
  // tests/fixtures/live-state/refresh.py.
  if (!snapshot.estate) {
    refuse(
      `${path.relative(ROOT, phasesFile)} carries no \\`estate\\`. Since schema 3 a phase ` +
        `REFERENCES the resource nodes it creates, and without them every apply phase ` +
        `folds as empty - which no case in here would report.`
    );
  }
  useEstate(snapshot.estate);
""",
    ),
]

# --- scripts/check-page-tense.mjs -------------------------------------------

EDITS[PAGE_TENSE_GATE] = [
    (
        """ *       ==== PAGE TENSE - begin ====
 *         figuresAreOlder(observation)
 *         envTense(observation, env)
 *         underWayHere(observation, env)
 *         nodeTense(node, record, envs, underWay)
 *       ==== PAGE TENSE - end ====
""",
        """ *       ==== PAGE TENSE - begin ====
 *         figuresAreOlder(observation)
 *         envTense(observation, env)
 *         underWayHere(observation, env)
 *         nodeTense(node, record, envs, underWay)
 *         historyTally(runs)
 *       ==== PAGE TENSE - end ====
 *
 * historyTally() joined them in 22 and is the same species: the run-history
 * badge scored a run that had not finished as one that had succeeded, because
 * it counted failures among completed runs and divided by every run there was.
""",
    ),
    (
        """const API = ["figuresAreOlder", "envTense", "underWayHere", "nodeTense"];""",
        """const API = ["figuresAreOlder", "envTense", "underWayHere", "nodeTense", "historyTally"];""",
    ),
]


# ------------------------------------------------------------ JSON migrations
#
# The two frozen stubs. They are DATA, so there is no anchor worth writing: the
# migration is structural, it is refused unless the file is exactly the shape it
# expects, and the output is the same 2-space JSON the fixtures are written in.


def migrate_node_states_stub(doc: dict) -> dict:
    """tests/fixtures/node-states/topology.json — schema 2 stub -> three contours."""
    if doc.get("schema") == 3:
        raise AlreadyApplied()
    if doc.get("schema") != 2 or "phases" not in doc:
        raise Refusal("tests/fixtures/node-states/topology.json is neither schema 2 nor schema 3")

    environments: dict[str, list[dict]] = {}
    phases = []
    for phase in doc["phases"]:
        own, touches = [], []
        for node in phase["nodes"]:
            # The teardown is the only VERB node in this stub: it is what a
            # cycle DOES, it carries no members, and node-states matches a
            # delete to it by environment rather than by address.
            if node.get("service") == "destroy":
                own.append(node)
            else:
                environments.setdefault(node["env"], []).append(node)
                touches.append({"node": node["id"], "verb": "creates"})
        if own:
            for node in own:
                touches += [
                    {"node": member["id"], "verb": "destroys"}
                    for member in environments.get(node["env"], [])
                ]
        phases.append(
            {
                "id": phase["id"],
                "n": phase["n"],
                "label": phase["label"],
                "workflow": phase["workflow"],
                "nodes": own,
                "touches": touches,
            }
        )

    return {
        "_": doc["_"],
        "_env": doc["_env"],
        "_contours": (
            "Schema 3. The estate holds what EXISTS and carries every member; the cycle "
            "holds what a run DOES and references the rest through `touches`. Kept as two "
            "contours here rather than flattened back for the test's convenience, because "
            "the join under test is exactly the resolution between them: read off "
            "phases[].nodes, index_members() returns an empty dict and every address in "
            "these fixtures reads as unknown."
        ),
        "schema": 3,
        "not_shown": doc["not_shown"],
        "estate": {
            "permanent": [],
            "environments": [
                {"id": env, "level": f"infra/envs/{env}", "nodes": nodes}
                for env, nodes in environments.items()
            ],
        },
        "cycle": {"phases": phases},
    }


def migrate_results_stub(doc: dict) -> dict:
    """tests/fixtures/results/topology.json — the frozen suite ids, one contour over."""
    if "cycle" in doc:
        raise AlreadyApplied()
    if "phases" not in doc:
        raise Refusal("tests/fixtures/results/topology.json has neither `phases` nor `cycle`")
    return {
        "_": (
            "Frozen: only the suite node ids, which is all the fold looks at. Under "
            "`cycle` since schema 3 — a suite is something a cycle DOES, so its node is a "
            "verb node and never part of the estate."
        ),
        "cycle": {"phases": doc["phases"]},
    }


JSON_MIGRATIONS = {
    "tests/fixtures/node-states/topology.json": migrate_node_states_stub,
    "tests/fixtures/results/topology.json": migrate_results_stub,
}


# --------------------------------------------------------------------- engine


def plan_text(path: Path, edits: list[tuple[str, str]]) -> tuple[str, bool]:
    """Apply every edit for one file to ONE string, in sequence. Never re-read.

    19g's defect exactly: every replacement computed from the ORIGINAL text and
    written one after another, so the second edit to a file discarded the first
    and the script said it had done both.
    """
    original = path.read_text(encoding="utf-8")
    text = original
    already = 0
    for anchor, replacement in edits:
        found = text.count(anchor)
        if found == 1:
            text = text.replace(anchor, replacement, 1)
            continue
        # Counted on the string as it stands, not on the original: an anchor
        # that a previous edit consumed is a defect in this script, and it must
        # not read as "already applied".
        if found == 0 and replacement in text:
            already += 1
            continue
        raise Refusal(
            f"{path.relative_to(ROOT)}: an anchor matched {found} times, expected exactly one.\n"
            f"    {anchor.strip().splitlines()[0][:100]}"
        )
    if already and already != len(edits):
        raise Refusal(
            f"{path.relative_to(ROOT)}: {already} of {len(edits)} edits are already applied. "
            f"That is a half-migrated file, which this script will not add to."
        )
    return text, already == len(edits)


def plan_json(path: Path, migrate) -> tuple[str, bool]:
    doc = json.loads(path.read_text(encoding="utf-8"))
    try:
        new = migrate(doc)
    except AlreadyApplied:
        return path.read_text(encoding="utf-8"), True
    return json.dumps(new, indent=2, ensure_ascii=False) + "\n", False


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--dry-run", action="store_true",
                        help="prove every anchor matches exactly once and write nothing")
    args = parser.parse_args(argv)

    planned: list[tuple[Path, str]] = []
    already: list[str] = []
    try:
        for name, edits in EDITS.items():
            path = ROOT / name
            if not path.is_file():
                raise Refusal(f"{name} does not exist")
            text, was_applied = plan_text(path, edits)
            (already.append(name) if was_applied else planned.append((path, text)))
        for name, migrate in JSON_MIGRATIONS.items():
            path = ROOT / name
            if not path.is_file():
                raise Refusal(f"{name} does not exist")
            text, was_applied = plan_json(path, migrate)
            (already.append(name) if was_applied else planned.append((path, text)))
    except Refusal as refusal:
        print(f"migrate-schema3: REFUSED\n{refusal}", file=sys.stderr)
        print("Nothing was written.", file=sys.stderr)
        return 2

    if already and planned:
        print(
            "migrate-schema3: REFUSED\n"
            f"already migrated: {', '.join(sorted(already))}\n"
            f"still to migrate: {', '.join(str(p.relative_to(ROOT)) for p, _ in planned)}\n"
            "A half-migrated tree is not a state this script will add to. Nothing was written.",
            file=sys.stderr,
        )
        return 2

    if already:
        print("migrate-schema3: already applied — every file is on schema 3, nothing to do.")
        print(f"  {len(already)} files: {', '.join(sorted(already))}")
        return 3

    if args.dry_run:
        print(f"migrate-schema3: {len(planned)} files would change; every anchor matched once.")
        for path, _ in planned:
            print(f"  {path.relative_to(ROOT)}")
        return 0

    # Every anchor in every file has matched by here, so this loop cannot stop
    # half way for a reason this script could have known about earlier.
    for path, text in planned:
        path.write_text(text, encoding="utf-8")
        print(f"  wrote {path.relative_to(ROOT)}")

    # NOT a string edit, on purpose: phases.json is generated, and a
    # hand-written copy of it beside its generator is a second definition of the
    # same snapshot. Patch the generator, then run it.
    refresh = ROOT / REFRESH
    before = (ROOT / "tests/fixtures/live-state/phases.json").read_text(encoding="utf-8")
    done = subprocess.run([sys.executable, str(refresh)], cwd=ROOT,
                          capture_output=True, text=True)
    if done.returncode != 0:
        print(f"migrate-schema3: {REFRESH} failed after the edits were written:\n"
              f"{done.stdout}{done.stderr}", file=sys.stderr)
        return 2
    after = (ROOT / "tests/fixtures/live-state/phases.json").read_text(encoding="utf-8")
    if after == before:
        print("migrate-schema3: refresh.py rewrote phases.json to what it already said. "
              "The snapshot has not picked up the estate.", file=sys.stderr)
        return 2
    print(f"  regenerated tests/fixtures/live-state/phases.json — {done.stdout.strip()}")

    print(f"migrate-schema3: applied to {len(planned)} files.")
    print("Now: make site-page && make site-data, then scripts/verify-schema3.sh")
    return 0


if __name__ == "__main__":
    sys.exit(main())
